#!/usr/bin/env python3
"""
Cross-reference between paths and autos.

Answers the two questions you actually ask:
  - "which autos use this path?"  (i.e. if I move a marker, what else breaks?)
  - "which paths does this auto run, in what order?"

Produces two things:
  pathplanner_map.html   interactive, click either side to cross-highlight
  PATHPLANNER_MAP.md     static tree, greppable and diffable in git

    python tools/pathplanner_map.py
    python tools/pathplanner_map.py --open
"""

import argparse
import glob
import json
import os
import sys
import time
import webbrowser
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pathplanner_audit import PP, ROOT, load, markers_of, path_sequence, replay  # noqa: E402

TEMPLATE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "map_template.html")
# Generated output lives beside this script, not at the repo root.
OUT_DIR = os.path.dirname(os.path.abspath(__file__))

ZONES = [("LT-", "Left Trench"), ("RT-", "Right Trench"), ("LB-", "Left Bump"),
         ("RB-", "Right Bump"), ("OUT-", "Outpost"), ("CTR-", "Center / Mid"),
         ("DEP-", "Depot"), ("S8-", "Shoot 8"), ("45-", "45° start"),
         ("BUMP-", "Bump traverse"), ("ZZ-", "Test / dev")]


def zone_of(name):
    for pre, label in ZONES:
        if name.startswith(pre):
            return label
    return "Unprefixed"


def collect():
    autos, paths = load("autos/*.auto"), load("paths/*.path")

    auto_paths, path_autos = {}, defaultdict(list)
    auto_meta = {}
    for aname, aj in autos.items():
        seq = []
        path_sequence(aj.get("command") or {}, seq)
        ordered = [v for k, v in seq if k == "path"]
        named = [v for k, v in seq if k == "named"]
        auto_paths[aname] = ordered
        for i, p in enumerate(ordered):
            path_autos[p].append(dict(auto=aname, step=i + 1))
        summary, _lines, findings = replay(aname, aj, paths)
        auto_meta[aname] = dict(
            paths=ordered, named=named, zone=zone_of(aname),
            errors=sum(1 for lvl, _ in findings if lvl == "ERROR"),
            warns=sum(1 for lvl, _ in findings if lvl == "WARN"),
            summary=summary)

    path_meta = {}
    for pname, pj in paths.items():
        ms = [dict(pos=round(pos, 2), name=nm, embedded=emb)
              for pos, nm, emb in markers_of(pj) if nm or emb]
        path_meta[pname] = dict(
            zone=zone_of(pname),
            waypoints=len(pj.get("waypoints") or []),
            markers=ms,
            autos=[u["auto"] for u in path_autos.get(pname, [])],
            shared=len({u["auto"] for u in path_autos.get(pname, [])}) > 1,
            orphan=not path_autos.get(pname))
    return path_meta, auto_meta


def write_md(pm, am, out):
    shared = sorted([p for p, d in pm.items() if d["shared"]],
                    key=lambda p: (-len(set(pm[p]["autos"])), p))
    orphans = sorted([p for p, d in pm.items() if d["orphan"]])

    L = ["# PathPlanner map", "",
         f"{len(pm)} paths, {len(am)} autos. "
         f"Generated by `tools/pathplanner_map.py` — do not hand-edit.", ""]

    L += ["## Shared paths — edit these carefully", "",
          "A marker change here lands in **every** auto listed. "
          "This is the table to check before you move a marker.", ""]
    if shared:
        L += ["| Path | Used by | Autos |", "|---|---|---|"]
        for p in shared:
            us = sorted(set(pm[p]["autos"]))
            L.append(f"| `{p}` | {len(us)} | " + ", ".join(f"`{u}`" for u in us) + " |")
    else:
        L.append("*None — every path belongs to exactly one auto.*")
    L.append("")

    if orphans:
        L += ["## Orphaned paths", "",
              "Referenced by no auto. Candidates for `pathplanner_archive/`.", ""]
        L += [f"- `{p}`" for p in orphans] + [""]

    L += ["## Autos → paths", ""]
    for zone_pre, zone_label in ZONES + [("", "Unprefixed")]:
        names = sorted(a for a, d in am.items() if d["zone"] == zone_label)
        if not names:
            continue
        L += [f"### {zone_label}", ""]
        for a in names:
            d = am[a]
            flag = f"  **{d['errors']} error(s)**" if d["errors"] else ""
            L.append(f"- **`{a}`**{flag}")
            for i, p in enumerate(d["paths"], 1):
                mk = pm.get(p, {}).get("markers", [])
                tag = " · " + " ".join(f"`{m['name']}@{m['pos']}`" for m in mk) if mk else ""
                sh = "  ⚠ shared" if pm.get(p, {}).get("shared") else ""
                L.append(f"  {i}. `{p}`{sh}{tag}")
            for n in d["named"]:
                L.append(f"  - ❌ NamedCommand `{n}` (never registered — auto fails to load)")
            L.append("")
    L += ["## Paths → autos", ""]
    for zone_pre, zone_label in ZONES + [("", "Unprefixed")]:
        names = sorted(p for p, d in pm.items() if d["zone"] == zone_label)
        if not names:
            continue
        L += [f"### {zone_label}", ""]
        for p in names:
            us = sorted(set(pm[p]["autos"]))
            where = ", ".join(f"`{u}`" for u in us) if us else "*orphan*"
            L.append(f"- `{p}` → {where}")
        L.append("")

    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(L))


def build(open_after=False, quiet=False):
    pm, am = collect()
    with open(TEMPLATE, encoding="utf-8") as f:
        html = f.read()
    html = (html.replace("__PATHS__", json.dumps(pm))
                .replace("__AUTOS__", json.dumps(am))
                .replace("__ZONES__", json.dumps([z[1] for z in ZONES] + ["Unprefixed"])))
    out_html = os.path.join(OUT_DIR, "pathplanner_map.html")
    with open(out_html, "w", encoding="utf-8") as f:
        f.write(html)
    out_md = os.path.join(OUT_DIR, "PATHPLANNER_MAP.md")
    write_md(pm, am, out_md)

    shared = [p for p, d in pm.items() if d["shared"]]
    orph = [p for p, d in pm.items() if d["orphan"]]
    if quiet:
        if open_after:
            webbrowser.open("file:///" + out_html.replace("\\", "/"))
        return out_html
    print(f"wrote {out_html}")
    print(f"wrote {out_md}")
    print(f"{len(pm)} paths, {len(am)} autos, {len(shared)} shared, {len(orph)} orphaned")
    if shared:
        print("\nshared paths (a marker edit hits every auto listed):")
        for p in sorted(shared, key=lambda p: -len(set(pm[p]["autos"]))):
            print(f"  {p:<22} {len(set(pm[p]['autos']))} autos: {', '.join(sorted(set(pm[p]['autos'])))}")
    if open_after:
        webbrowser.open("file:///" + out_html.replace("\\", "/"))
    return out_html


def watch(args):
    build(open_after=True, quiet=True)
    print("Watching. Save in PathPlanner, then refresh the browser tab. Ctrl+C to stop.")
    last = None
    try:
        while True:
            st = tuple(sorted((f, os.path.getmtime(f))
                              for f in glob.glob(os.path.join(PP, "**", "*.*"), recursive=True)))
            if st != last:
                last = st
                build(quiet=True)
                print(f"  rebuilt {time.strftime('%H:%M:%S')}")
            time.sleep(1.0)
    except KeyboardInterrupt:
        print("\nstopped.")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--open", action="store_true")
    ap.add_argument("--watch", action="store_true", help="rebuild on every save")
    args = ap.parse_args()
    if args.watch:
        return watch(args)
    build(open_after=args.open)
    return 0


if __name__ == "__main__":
    sys.exit(main())
